# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.5"

required_plugins = %w( vagrant-vbguest )
required_plugins.each do |plugin|
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

Vagrant.configure("2") do |config|

	config.ssh.forward_agent = true

	config.vm.synced_folder "../ansible", "/ansible",create:true
	config.vm.synced_folder "../shared/mpfwww", "/home/vagrant/myshared", create:true
	
	config.vm.box = "geerlingguy/centos6"

		config.vm.provider "virtualbox" do |vb|
			vb.name = "SESION8_CENTOS6_FIN"
			vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
			vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
		end
	config.vm.define "web", primary: true do |web|
		web.vm.network :private_network, ip: "192.168.33.50"
		web.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true
		web.vm.network :forwarded_port, guest: 443, host: 8081, auto_correct: true
	
		web.vm.hostname = "ansibleMpwar"
		
		web.vm.provision :shell, path: "shell/vagrant_main_provision_mpf.sh"
		
   end

end